### ISSUE TITLE
Possible options for different transition types?

### ISSUE THREAD

**Issue by mxmilkiib** [my-slab/camelot-wheel#1]
Hi! There are a couple of Android apps that I use for harmonic mixing that provide more specific/detailed options for possible transitions.

I'll attach some screenshots.

Could it be possible to implement these in the system?

![Screenshot_20240107-064706_Harmonic Mix.png](https://github.com/geeves/camelot-wheel/assets/108225/fceb7863-2e12-4692-ade3-53a1dae2e7f3)

![Screenshot_20240107-064710_Harmonic Mix.png](https://github.com/geeves/camelot-wheel/assets/108225/46401311-9240-4ff9-9065-95351785b671)

![Screenshot_20240107-064726_Harmonic Mix.png](https://github.com/geeves/camelot-wheel/assets/108225/fea53110-b6d5-4957-a7ed-c85e3ebaac31)

![Screenshot_20240107-064721_Harmonic Mix.png](https://github.com/geeves/camelot-wheel/assets/108225/c3f9c2a9-4fbc-43da-bd07-beea441c41bf)

![Screenshot_20240107-065041.png](https://github.com/geeves/camelot-wheel/assets/108225/1bf573ed-7668-419d-8b19-e0e079450370)

![Screenshot_20240107-065044.png](https://github.com/geeves/camelot-wheel/assets/108225/57149444-e131-4c3e-8fc1-8833aa302adb)

![Screenshot_20240107-065032.png](https://github.com/geeves/camelot-wheel/assets/108225/99157d21-9c0c-4d79-8406-bc0404c97399)

![Screenshot_20240107-065035.png](https://github.com/geeves/camelot-wheel/assets/108225/3d8bb54b-ec51-40ec-af43-46247d522068)

![Screenshot_20240107-065058.png](https://github.com/geeves/camelot-wheel/assets/108225/bbfa8267-f87d-422d-b5ad-6ca257816ed8)

![Screenshot_20240107-065102.png](https://github.com/geeves/camelot-wheel/assets/108225/68e86d37-e5f4-44ac-9556-92f55218d7fe)

![Screenshot_20240107-065148.png](https://github.com/geeves/camelot-wheel/assets/108225/800c975a-b3a1-40da-ad87-b3bd4b131359)

![Screenshot_20240107-065108.png](https://github.com/geeves/camelot-wheel/assets/108225/0e1a8851-1c73-4893-a33e-087ba5d4cd1d)

![Screenshot_20240107-070152.png](https://github.com/geeves/camelot-wheel/assets/108225/f64d3443-0b17-4031-a192-03b22ba41f28)

![Screenshot_20240107-065130.png](https://github.com/geeves/camelot-wheel/assets/108225/5de4e1b7-a6dc-4b0d-a230-e91d92a1631a)

**Comment by my-slab** [comment]
Hey @mxmilkiib , I didn't know about these transition options, thanks for raising. I don't think so, I don't really play fuser anymore and the game isn't supported other than modding so I'll probably just archive this repo if anything.
